name: car_tracking_new
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.20.2
  fl_chart: ^0.63.0
  shared_preferences: ^2.2.2
  excel: ^2.1.0
  path_provider: ^2.1.2
  animate_do: ^3.1.2
  permission_handler: ^11.0.1
  file_saver: ^0.2.9
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  mobile_scanner: ^6.0.7
  provider: ^6.1.2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # ✅ Add package to generate app icons

flutter:
  uses-material-design: true
  assets:
    - assets/mercedes_logo.jpg
    - assets/appicon.jpeg  # ✅ Ensure appicon.jpeg exists in assets folder

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon.jpeg"  # ✅ Set custom app icon
  adaptive_icon_background: "#ffffff"  # ✅ Set background for adaptive icons (Android 8+)
